name: Push action - build and push image to DockerHub

on:
  push:
    branches: [main]

jobs:
  build-push-images:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.PAT }}
          repository: pawelp29/ip_time
          context: ./
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          file: ./Dockerfile
          push: true
          labels: ${{ steps.meta.output.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
      
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
